//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.21 at 12:03:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pis.predmety.fiit.stuba.sk/pis/notificationservices/sms/types")
package sk.stuba.fiit.predmety.pis.pis.notificationservices.sms.types;
